    // printf("%d\n", matrix[0][0]);
    // printf("%d\n", matrix[0][1]);
    // printf("%d\n", matrix[0][2]);
    // printf("%d\n", matrix[1][0]);
    // printf("%d\n", matrix[1][1]);
    // printf("%d\n", matrix[1][2]);
    // printf("%d\n", matrix[2][0]);
    // printf("%d\n", matrix[2][1]);
    // printf("%d\n", matrix[2][2]);